=== anjeL0L/liga-mx-xml/dtd/resultados.dtd
<!ELEMENT liga (jornada+)>
<!ELEMENT jornada (partido+)>
<!ATTLIST jornada numero CDATA #REQUIRED>
<!ATTLIST jornada fecha CDATA #REQUIRED>

<!ELEMENT partido (equipoLocal, equipoVisitante, estadio)>
<!ATTLIST partido id ID #REQUIRED>
<!ATTLIST partido estado CDATA #REQUIRED>

<!ELEMENT equipoLocal (marcador, estadisticas?)>
<!ATTLIST equipoLocal nombre CDATA #REQUIRED>

<!ELEMENT equipoVisitante (marcador, estadisticas?)>
<!ATTLIST equipoVisitante nombre CDATA #REQUIRED>

<!ELEMENT marcador (#PCDATA)>
<!ELEMENT estadio (#PCDATA)>

<!ELEMENT estadisticas (posesion, tiros, faltas)>
<!ELEMENT posesion (#PCDATA)>
<!ELEMENT tiros (#PCDATA)>
<!ELEMENT faltas (#PCDATA)>

=== anjeL0L/liga-mx-xml/xml/resultados-invalido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "../dtd/resultados.dtd">
<liga>
    <jornada numero="10" fecha="2026-09-27">
        <!-- Error 1: Falta atributo 'estado'. Error 2: Dos equipos locales y sin visitante -->
        <partido id="P002">
            <equipoLocal nombre="Cruz Azul"><marcador>2</marcador></equipoLocal>
            <equipoLocal nombre="Chivas"><marcador>1</marcador></equipoLocal>
            <estadio>Estadio Azteca</estadio>
        </partido>
    </jornada>
</liga>

=== anjeL0L/liga-mx-xml/xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "../dtd/resultados.dtd">
<liga>
    <jornada numero="10" fecha="2026-09-27">
        <partido id="P001" estado="Finalizado">
            <equipoLocal nombre="Pumas UNAM">
                <marcador>1</marcador>
                <estadisticas>
                    <posesion>55%</posesion>
                    <tiros>12</tiros>
                    <faltas>10</faltas>
                </estadisticas>
            </equipoLocal>
            <equipoVisitante nombre="Club América">
                <marcador>0</marcador>
                <estadisticas>
                    <posesion>45%</posesion>
                    <tiros>8</tiros>
                    <faltas>14</faltas>
                </estadisticas>
            </equipoVisitante>
            <estadio>Olímpico Universitario</estadio>
        </partido>
    </jornada>
</liga>
